HeatTemplateFormatVersion: '2012-12-12'
Description: 'Glance'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  GlanceDSN:
    Description: DSN for connecting to glance database
    Type: String
  GlanceImage:
    Type: String
  KeystoneHost:
    Type: String
  ServicePassword:
    Description: admin_password for setting up auth in keystone.
    Type: String
  RabbitHost:
    Type: String
  RabbitPassword:
    Type: String
Resources:
  AccessPolicy:
    Type: OS::Heat::AccessPolicy
    Properties:
      AllowedResources: [ Glance ]
  User:
    Type: AWS::IAM::User
    Properties:
      Policies: [ { Ref: AccessPolicy } ]
  Key:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User
  Glance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        {Ref: GlanceImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      OpenStack::Role: stateless
      OpenStack::ImageBuilder::Elements: [ glance ]
      heat: 
        access_key_id:
          Ref: Key
        secret_key:
          Fn::GetAtt: [ Key, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: Glance
      keystone:
        host: {Ref: KeystoneHost}
      glance:
        db: {Ref: GlanceDSN}
      service-password: {Ref: ServicePassword}
      rabbit:
        host: {Ref: RabbitHost}
        password: {Ref: RabbitPassword}
      swift:
        store_user: ''
        store_key: ''
