HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - Keystone'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  KeystoneDSN:
    Description: DSN for connecting to keystone
    Type: String
  KeystoneImage:
    Type: String
  AdminToken:
    Type: String
Resources:
  ApiAccessPolicy:
    Type: OS::Heat::AccessPolicy
    Properties:
      AllowedResources: [ KeystoneLaunch, Keystone ]
  ApiUser:
    Type: AWS::IAM::User
    Properties:
      Policies: [ { Ref: ApiAccessPolicy } ]
  ApiKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: ApiUser
  Keystone:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        {Ref: KeystoneImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      OpenStack::Role: stateless
      OpenStack::ImageBuilder::Elements: [ keystone ]
      heat: 
        access_key_id:
          Ref: ApiKey
        secret_key:
          Fn::GetAtt: [ ApiKey, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: Keystone
      admin-token: {Ref: AdminToken}
      keystone:
        db: {Ref: KeystoneDSN}
