HeatTemplateFormatVersion: '2012-12-12'
Description: 'Group of Nova Computes'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: baremetal
  NovaImage:
    Type: String
  KeystoneHost:
    Type: String
  ServicePassword:
    Description: admin_password for setting up auth in nova.
    Type: String
  QuantumHost:
    Type: String
  RabbitHost:
    Type: String
  RabbitPassword:
    Type: String
  NovaInterfaces:
    Type: String
    Default: eth0
  NovaComputeDriver:
    Type: String
    Default: libvirt.LibvirtDriver
  NovaApiHost:
    Type: String
  GlanceHost:
    Type: String
  NovaComputeTemplate:
    Type: String
    Default: https://raw.github.com/SpamapS/templates/MERGE/nova-compute-instance.yaml
  NovaDSN:
    Type: String
  QuantumDSN:
    Type: String
Resources:
  NovaCompute0:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NovaImage: {Ref: NovaImage}
        InstanceType: {Ref: InstanceType}
        KeyName: {Ref: KeyName}
        KeystoneHost: {Ref: KeystoneHost}
        ServicePassword: {Ref: ServicePassword}
        QuantumHost: {Ref: QuantumHost}
        RabbitHost: {Ref: RabbitHost}
        RabbitPassword: {Ref: RabbitPassword}
        NovaInterfaces: {Ref: NovaInterfaces}
        NovaComputeDriver: {Ref: NovaComputeDriver}
        NovaApiHost: {Ref: NovaApiHost}
        GlanceHost: {Ref: GlanceHost}
        NovaDSN: {Ref: NovaDSN}
        QuantumDSN: {Ref: QuantumDSN}
      TemplateURL: {Ref: NovaComputeTemplate}
