HeatTemplateFormatVersion: '2012-12-12'
Description: 'Quantum'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  QuantumDSN:
    Description: DSN for connecting to quantum database
    Type: String
  QuantumImage:
    Type: String
  KeystoneHost:
    Type: String
  ServicePassword:
    Description: admin_password for setting up auth in quantum.
    Type: String
  TemplateURL:
    Type: String
    Default: https://raw.github.com/openstack-ops/templates/master/
  RabbitHost:
    Type: String
  RabbitPassword:
    Type: String
  QuantumInterfaces:
    Type: String
    Default: eth0
Resources:
  AccessPolicy:
    Type: OS::Heat::AccessPolicy
    Properties:
      AllowedResources: [ Quantum ]
  User:
    Type: AWS::IAM::User
    Properties:
      Policies: [ { Ref: AccessPolicy } ]
  Key:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User
  Quantum:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        {Ref: QuantumImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      OpenStack::Role: networking
      OpenStack::ImageBuilder::Elements: [ quantum ]
      heat: 
        access_key_id:
          Ref: Key
        secret_key:
          Fn::GetAtt: [ Key, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: Quantum
      keystone:
        host: {Ref: KeystoneHost}
      quantum:
        ovs_db: {Ref: QuantumDSN}
      service-password: {Ref: ServicePassword}
      admin-password: {Ref: ServicePassword}
      rabbit:
        host: {Ref: RabbitHost}
        password: {Ref: RabbitPassword}
      swift:
        store_user: ''
        store_key: ''
      interfaces:
        control: {Ref: QuantumInterfaces}
