HeatTemplateFormatVersion: '2012-12-12'
Description: 'Dedicated RabbitMQ Server'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  RabbitMQImage:
    Type: String
Resources:
  RabbitMQ:
    Type: AWS::EC2::Instance
    Metadata:
      OpenStack::Role: stateful
      OpenStack::ImageBuilder::Elements: [ rabbitmq-server ]
      rabbitmq:
        password_handle: {Ref: RabbitMQPasswordHandle}
    Properties:
      ImageId:
        {Ref: RabbitMQImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
  RabbitMQPasswordHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  RabbitMQPassword:
    DependsOn: RabbitMQ
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: {Ref: RabbitMQPasswordHandle}
      Timeout: 60
Outputs:
    RabbitMQHost: 
        Fn::GetAtt: [ RabbitMQ , PrivateIp ]
    RabbitMQPassword:
        Fn::GetAtt: [ RabbitMQPassword, Data ]
